### ISSUE TITLE
Feature Request: Hotkey to show help

### ISSUE THREAD

**Issue by anoduck** [xyproto/o#6]
Been using O as a terminal based markdown editor, and I do like how it handles markdown files. There is a niche market there, that O is well suited for. 

The menu hotkey is really throwing me for a loop. In every other application, `ctrl-o` opens a file, not the menu. Could not this be mapped to `ctrl-m`, which would make more sense. 

Also, a help page which could be opened with `ctrl-h`, and on that help page a reference of the other hotkeys available. This would be really a big help. 

A hotkey to enable word wrap(`ctrl-r` or `ctrl-w`), would be awesome, and a hotkey to insert the date (`ctrl-i` or `ctrl-d`).

**Comment by xyproto** [comment]
These are great suggestions, but ctrl-h is unfortunatley interpreted as backspace by most VT100 terminal emulators. And ctrl-m is interpreted as carriage return.

For `ko` on the other hand, the GUI version of `o`, this would be easy to implement.

VT100 is a bit dumb and limited, but then again, `o` should work in almost any terminal emulator, even over ssh to older systems.

https://www.vt100.net/docs/vt100-ug/chapter3.html#T3-5

**Comment by anoduck** [comment]
Well, that explains some things, running `o` in kitty... cool beans. Appreciate your openness. I will write a little blurb about it and share it on social media with a group for Unix users I Patreon.

**Comment by xyproto** [comment]
Thanks, @anoduck.
